# Generated by Django 5.0.2 on 2025-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
