# Generated by Django 6.0.1 on 2026-01-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary of the conversation', null=True),
        ),
    ]
