# Generated by Django 5.1.7 on 2025-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
