# Generated by Django 6.0.1 on 2026-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
