# Generated by Django 5.1.7 on 2025-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_history_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
