# Generated by Django 5.2.4 on 2025-07-07 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_fileupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='fileupload',
            constraint=models.UniqueConstraint(fields=('user', 'file_hash'), name='unique_user_file_hash'),
        ),
    ]
