# Generated by Django 5.0.2 on 2025-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
