# Generated by Django 5.0.2 on 2025-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_filelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file_hash",
            field=models.CharField(max_length=64),
        ),
    ]
